# https://thedaviddias.dev/blog/how-to-deploy-your-nextjs-app-on-netlify-using-github-actions/#configure-netlify
[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"
