version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  version: 2
  lint-and-test:
    jobs:
      - lint
      - ts-check
      - test:
          requires:
            - ts-check
            - lint

jobs:
  lint:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint

  ts-check:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: ts-check
          command: npm run ts-check

  test:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: tests
          command: npm run test
#
#
# TODO: get build URL from vercel to use as client for cypress tests
