name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    # adapted from https://gist.github.com/ttsalpha/9e007ab145482794f2b1b927c7c5af6a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm install
      - uses: actions/cache@v2
        id: cache-install
        with:
          path: "."
          key: ${{ github.WORKFLOW }}

  lint:
    # adapted from https://gist.github.com/ttsalpha/9e007ab145482794f2b1b927c7c5af6a
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        id: restore-install
        with:
          path: "."
          key: ${{ github.WORKFLOW }}
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [install, lint]
    steps:
      - uses: actions/cache@v2
        id: restore-install
        with:
          path: "."
          key: ${{ github.WORKFLOW }}
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [install, lint, test]
    steps:
      - uses: actions/cache@v2
        id: restore-install
        with:
          path: "."
          key: ${{ github.WORKFLOW }}
      - run: npm run build
